### ISSUE TITLE
Currencies and sale prices

### ISSUE THREAD

**Issue by VirAlex** [algolia/algolia-react-boilerplate#188]
@longjasonm do you think you have any spare time to tackle this one?

**Comment by matthew1809** [comment]
Spec:

- Currency symbol on left or right according to the currency set in configuration
- Price and sale price components dynamic according to whether there is a sale price
- Dealing with commas and full stop formatting i.e. price separators

Configuration changes:
- https://github.com/algolia/algolia-react-boilerplate/blob/develop/src/config/currencyConfig.js#L15
- new attribute in hitsConfig https://github.com/algolia/algolia-react-boilerplate/blob/develop/src/config/hitsConfig.js#L13
