### ISSUE TITLE
Issue on Carousel

### ISSUE THREAD

**Issue by VirAlex** [algolia/algolia-react-boilerplate#230]
I think it's due to new React, some value of the carousel are no longer recognized:
![Screenshot 2022-06-23 at 12 08 07](https://user-images.githubusercontent.com/22235112/175274861-39587de7-2f03-42af-9141-d14c42e20fa0.png)

**Comment by matthew1809** [comment]
Not due to new React, due to including the Horizontal Slider from Algolia
https://github.com/algolia/ui-components/blob/master/packages/horizontal-slider-react
