### ISSUE TITLE
Autocomplete update V2

### ISSUE THREAD

**Issue by VirAlex** [algolia/algolia-react-boilerplate#241]
What about autocomplete Widget? 
[Link](https://www.algolia.com/doc/ui-libraries/autocomplete/solutions/advanced-federated-search-experience-for-ecommerce/)
[Link 2](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/getting-started/)

Feel free to write anything on this issue, it's a question, an investigation. 
We have to think about keep our FS like it is, or improve our FS to an Autocomplete one, using Algolia's feature.

1. Advantages to keep our FS :

- I think to be honest it's functional, and it have all Autocomplete feature(Recently Searches, Suggestions,...) @VirAlex 
- 

2. Advantages to change to [Autocomplete](https://www.algolia.com/doc/ui-libraries/autocomplete/solutions/advanced-federated-search-experience-for-ecommerce/)

- Use our feature and our widgets @VirAlex 
- I think many people, of course the Smooth Engineers will see this feature and they'll want it in their Demo @VirAlex 
-

**Comment by matthew1809** [comment]
@VirAlex closing this for now as there is no demonstrated demand
