### ISSUE TITLE
Price Slider Causing Flickering

### ISSUE THREAD

**Issue by diegolarraz** [algolia/algolia-react-boilerplate#258]
https://user-images.githubusercontent.com/58960798/177310055-c260a427-ed99-4a99-a4d0-1069770a5dc9.mov

**Comment by VirAlex** [comment]
I think it comes from Trend Facet I tried something to change the order of facets and without trends it works:
https://share.getcloudapp.com/QwunL0Je

**Comment by diegolarraz** [comment]
> I think it comes from Trend Facet I tried something to change the order of facets and without trends it works: https://share.getcloudapp.com/QwunL0Je

thank you @VirAlex 🙏
