### ISSUE TITLE
Window Resize Listener - Should be moved to global state

### ISSUE THREAD

**Issue by diegolarraz** [algolia/algolia-react-boilerplate#260]
As you can see in the image below if we console log the place of origin wen we `useScreenSize`, it creates a new event listener for every time the hook `useScreenSize` is called. Way to solve this is to move it into global state. 

The setter function can be called once in the app level and we save it in an atom which we then use in our application for read purposes only. 

<img width="892" alt="Screenshot 2022-07-05 at 12 48 12" src="https://user-images.githubusercontent.com/58960798/177323318-1e19a22c-4d8c-4523-a5ae-4c9e09908877.png">

**Comment by VirAlex** [comment]
Nice, it could be cleaner effectively @diegolarraz
