### ISSUE TITLE
Step by step guide for SEs to set up the boilerplate

### ISSUE THREAD

**Issue by matthew1809** [algolia/algolia-react-boilerplate#303]
- Start with no config set
- Try to define the right approach

**Comment by BenDanielGreep** [comment]
Spec:
- Create a new Boilerplate Template without an index inside, and with most features turned off by default
- Create short videos demonstrating how to edit each file, following the README
- Publish  [somehow]

**Comment by matthew1809** [comment]
https://docs.google.com/document/d/1mqKYoKn4gcEzlYHpQvbvuI_84OoFYNIgucuYoISgawg/edit

**Comment by matthew1809** [comment]
- Dynamic Facets
- Carousels
- Injected Content
- Trending
- Related
- FBT
- Navigation
