### ISSUE TITLE
About - Description on Github

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#311]
Heya! I noticed the project is missing a description in the about section on github.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/87393193/183691035-17f8a38e-e3e8-4bf7-b13d-d2aba504287a.png">

One benefit is it will look more complete in search results.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/87393193/183691542-48e31ed2-d278-4e93-bd3e-4481a67bb7ce.png">

**Comment by VirAlex** [comment]
Thank you @jeffrey-slentz-algolia 🙏

**Comment by matthew1809** [comment]
Done, thanks @VirAlex for that, and for flagging @jeffrey-slentz-algolia!
