### ISSUE TITLE
showMore Console Error on SRP on price-refactor branch

### ISSUE THREAD

**Issue by BenDanielGreep** [algolia/algolia-react-boilerplate#312]
<img width="1025" alt="Screenshot 2022-08-10 at 09 18 35" src="https://user-images.githubusercontent.com/72299424/183856576-fb0fb8f7-47b6-4cab-8053-8e76f79282ad.png">

**Comment by BenDanielGreep** [comment]
NB there's a scrolling error that might be related? It might be the Trending items images unloading and reloading?
Not sure- link below:

https://share.getcloudapp.com/Wnu7OgNv

**Comment by matthew1809** [comment]
Does this occur in prod @BenDanielGreep?
