### ISSUE TITLE
personalization Impact atom missing

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#330]
Adding `personalizationImpact` to `personaConfig.js` doesn't affect the persona

for example:
```js
  {
    value: 'stephen_james',
    label: 'Stephen, JK Owner',
    description: 'Stephen James owns a model JK',
    type: 'persona',
    personalizationImpact:98,
    personalizationFilters: [ 
      "models:JK<score=2>",
    ],
  },
```

files affected:
`src/config/personaConfig.js`
`README.md`
`src/components/federatedSearch/FederatedSearch.jsx`

**Comment by matthew1809** [comment]
Impact is a global setting, not specific per user https://github.com/algolia/algolia-react-boilerplate/blob/develop/src/config/personaConfig.js#L6

**Comment by jeffrey-slentz-algolia** [comment]
might be good to have the control of a score per user, but global is fine too! Thanks 👍
