### ISSUE TITLE
slow performance with big images

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#331]
my dataset had big images, had to swap them for smaller images to improve the time it took them to load.
also, product details page now uses the smaller image 

suggested fix:
add a new `hitsConfig.js` attribute for thumbnail images to suggest to new users that a thumbnail will help search performance
use the big image for the product details page

OR

lazy load the images instead of blocking/slowing the animations

**Comment by matthew1809** [comment]
Good idea, and thanks for suggesting fixes!
