### ISSUE TITLE
headerConfig filter is retrictive

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#334]
`src/config/headerConfig.js` has some examples but the filter attribute is not extensible

If I wanted to have another filter or a nested filter, I can't -- I'm restricted to my category definition in `src/config/categoryConfig.js`

Instead, `filter` should be generalized and let me define what filters I want to apply, like a regular queryParam

```js
  default: [
    {
      name: 'All',
      type: 'filter',
      filter: '',
      url: '/search',
    },
    {
      name: 'Jeep Interior',
      type: 'filter',
      filter: 'Jeep Interior',
      url: '/JeepInterior',
    },
```

**Comment by matthew1809** [comment]
Don't think I understand @jeffrey-slentz-algolia, is the restriction that it can only filter by a single attribute?

**Comment by jeffrey-slentz-algolia** [comment]
Yes exactly -- The config here should be flexible so that I can just pass whatever filters I need.

For example:
```JS
filters: '(category:Book OR category:Ebook) AND _tags:published'
```

We already have `filters` well defined and documented in Algolia's query params, so we could just use those.

I am realizing there's a dependency when visiting the category page and it adds that filter context to the visuals of the search bar though 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/87393193/185155669-321cda04-6adb-459e-b94f-b83b6e581916.png">

**Comment by matthew1809** [comment]
Tricky one, it's a great idea to not depend on the single category attribute, perhaps we could use the name attribute though, which is also passed. I think this is a valid issue, and can be worked on, will put it in this weeks sprint, thanks @jeffrey-slentz-algolia
