### ISSUE TITLE
scroll position not reset on SRP -> PDP

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#345]
When scrolled down on the search results page and clicking on an item, scroll position is not reset.

**Comment by VirAlex** [comment]
Hello @jeffrey-slentz-algolia can you just maybe record what's wrong? I'm not sure than I have the same issue:
https://share.getcloudapp.com/jkuW7Enq

**Comment by jeffrey-slentz-algolia** [comment]
Looks like it's because your PDP fits inside your vertical screen height. If it had a scroll-bar, it might present the issue. You can arbitrarily increase the height of the PDP to test?
