### ISSUE TITLE
federated search - category link not working

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#352]
`src/components/federatedSearch/components/Category.jsx` uses the wrong version of state. not an easy fix though because changing it from 

```JS
navigate('/search', {
    state: `${federatedCategoriesAttribute}:"${hit.label}"`,
});
```

to

```JS
navigate('/search', {
    state: {
        type: 'filter',
        action:`${federatedCategoriesAttribute}:"${hit.label}"`, 
    }
});
```

1) doesn't fix the current refinements
2) adds a "category" filter to the search bar which may or may not be expected behavior

**Comment by VirAlex** [comment]
👋 if you ant to test, when you'll have time it didn't work effectively. Thanks to four feedback.
#353
