### ISSUE TITLE
navigationConfig: Apostrophe in RawFilter causes error

### ISSUE THREAD

**Issue by jeffrey-slentz-algolia** [algolia/algolia-react-boilerplate#373]
If your filter attribute has a `'` single quote in it, it breaks.

**Comment by HugoWith** [comment]
> If your filter attribute has a ' single quote in it, it breaks.

Hey @jeffrey-slentz-algolia 
Thanks a lot for spotting so many fixes and bugs ! Really apreciate your feedbacks. 😊
I can't replicate this issue. Do you have an example by any chance ? 
Thanks !

**Comment by wahba404** [comment]
```
    // For an uilisation of your own made filter
    {
      name: `Women's Shoes`,
      type: 'rawFilter',
      filter: '',
      rawFilter:
        "hierarchicalCategories.lvl1:`Shoes > Women's Shoes`",
      url: '/annafield',
    },
```

**Comment by jeffrey-slentz-algolia** [comment]
https://github.com/algolia/algolia-react-boilerplate/tree/apostrophe-bug-example

here's a replication

**Comment by HugoWith** [comment]
Hello @jeffrey-slentz-algolia , @wahba404 
Thanks for expanded on that one 👆. 

Just tried by escaping the character like so : 

`    // For an uilisation of your own made filter
    {
      name: `Women's Shoes`,
      type: 'rawFilter',
      filter: '',
      rawFilter:
        "hierarchicalCategories.lvl1:'Shoes > Women\'s Shoes'",
      url: '/annafield',
    },`
    
    It seems to work fine 😊. 
    Let me know how it goes on your side of things !

**Comment by HugoWith** [comment]
Hello @jeffrey-slentz-algolia , @wahba404
Thanks for expanded on that one 👆.

Just tried by using "´" as an apostrophe and the error seems to be gone :

```
    // For an uilisation of your own made filter
    {
      name: `Women's Shoes`,
      type: 'rawFilter',
      filter: '',
      rawFilter:
        "hierarchicalCategories.lvl1:'Shoes > Women´s Shoes'",
      url: '/annafield',
    }
```

Let me know how it goes on your side of things 😊 !
