### ISSUE TITLE
Multiple unresolved merge conflicts have been committed.

### ISSUE THREAD

**Issue by JellyTitan** [algolia/algolia-react-boilerplate#488]
Can't load content, getting `Uncaught SyntaxError: Unexpected token '<<' (at predictConfig.js:8:1)` 

It looks like there are 24 unresolved merge conflicts over several files:
src/components/cart/ArticlesCard.jsx
src/components/fbtPdp/FbtAddAll.jsx
src/config/cartFunctions.js
src/config/predictConfig.js
src/pages/productDetailsPage/ProductDetails.jsx

**Comment by matthew1809** [comment]
Hi there, thanks for flagging! We'd spotted but haven't had a chance to fix yet, expect it to be fixed tomorrow though.

**Comment by matthew1809** [comment]
Resolved
