### ISSUE TITLE
Injected content requires the influencers index to exist even if not used
Matthew Foyle


### ISSUE THREAD

**Issue by VirAlex** [algolia/algolia-react-boilerplate#497]
<p>You can inject content in two ways:<br/></p><ol><li>Via rules in the same index</li><li>Via records in a different index</li></ol><p><br/>We should not crash the app when injected content is turned on, should option two not be set up.</p>

https://app.clickup.com/t/2zxdbc0

**Comment by wahba404** [comment]
What is the fix here? Should we just remove that key value pair from the config file?
