### ISSUE TITLE
Hit Pice component Issue

### ISSUE THREAD

**Issue by VirAlex** [algolia/algolia-react-boilerplate#559]
👋 , when I cloned the repo, I had an issue with the price component, and the fact than it returns, if there is no price for a hit, the entire object of hit.

`  const hitPrice = get(hit, price) ? get(hit, price) : hit`

Maybe the condition should be a random number or an other thing actually on my demo I fixed it with :
`  const hitPrice = get(hit, price) ? get(hit, price).toFixed(2) : Math.floor(Math.random() * 1000).toFixed(2)`

🙏

**Comment by HugoWith** [comment]
Well spotted ! Fix is here : https://github.com/algolia/algolia-react-boilerplate/pull/560
