### ISSUE TITLE
Issue on Injected content

### ISSUE THREAD

**Issue by VirAlex** [algolia/algolia-react-boilerplate#567]
Image maybe changed or removed
![Screenshot 2023-01-10 at 14 11 51](https://user-images.githubusercontent.com/22235112/211560675-828b1262-4515-455d-985c-81ecda6697dd.png)

**Comment by HugoWith** [comment]
<img width="521" alt="Screenshot 2023-01-10 at 14 33 59" src="https://user-images.githubusercontent.com/47173348/211565161-f2149318-11c7-4e4f-8a8a-be50ce067eb8.png">

Corrected thanks Alex :)
